pipeline {
    agent any

    environment {
        DOCKER_BACKEND_IMAGE = "whattoeat-backend"
        DOCKER_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
                dir('backend/whattoeat') {
                    sh 'pwd'
                }
            }
        }

        stage('Backend Build') {
            steps {
                sh './gradlew clean build -x test'
            }
        }

        stage('Docker Build') {
            steps {
                sh "docker build -t ${DOCKER_BACKEND_IMAGE}:${DOCKER_TAG} ."
            }
        }

        stage('Deploy') {
            steps {
                sh """
                    docker stop ${DOCKER_BACKEND_IMAGE} || true
                    docker rm ${DOCKER_BACKEND_IMAGE} || true
                    docker run -d --name ${DOCKER_BACKEND_IMAGE} \
                        -p 8080:8080 \
                        ${DOCKER_BACKEND_IMAGE}:${DOCKER_TAG}
                """
            }
        }
    }
}